import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#6CB66F',
    position: 'relative',
  },
  backgroundSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  avatarContainer: {
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  avatar: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  title: {
    color: '#FFFFFF',
    fontSize: 40,
    fontWeight: '600',
    marginBottom: 30,
    letterSpacing: 0.5,
  },
  formContainer: {
    width: '100%',
    maxWidth: 380,
    height: 380,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  formBlob: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  blobSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  form: {
    width: '85%',
    zIndex: 2,
    paddingHorizontal: 20,
  },
  input: {
    width: '100%',
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#E8E8E8',
    borderWidth: 0,
    marginBottom: 16,
    fontSize: 16,
    color: '#333',
  },
  button: {
    backgroundColor: '#2D6F45',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  signupContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  signupText: {
    color: '#FFFFFF',
    fontSize: 16,
    marginRight: 4,
  },
  link: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '500',
  },
  linkUnderline: {
    textDecorationLine: 'underline',
  },
});